companieshouse/docs.developer.ch.gov.uk

.idea/$PRODUCT_WORKSPACE_FILE$, .idea/.gitignore, .idea/codeStyles/codeStyleConfig.xml, .idea/compiler.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, Makefile, docs.developer.ch.gov.uk.iml, pom.xml
=> Basic setup for Developer hub documentation project

src/main/resources/templates/fragments/betabanner.html, src/main/resources/templates/fragments/footer.html, src/main/resources/templates/fragments/header.html, src/main/resources/templates/fragments/userBar.html, src/main/resources/templates/layouts/baseLayout.html
Created various fragment files for the baselayout.html and also chaned baselayout file to remove company accounts references.
=> Creation of various fragment files

pom.xml, routes.yaml
=> Fixed pom structure to comply with companies house structure

src/main/resources/templates/application.properties
Removal of duplicate application.properties
FA-276
*  Bug fix
=> Removed duplicate application.properties

src/main/resources/templates/dev-hub/createAccount.html, src/main/resources/templates/dev-hub/home.html
Made createAccount page compliant with requirements of current dev hub prototype
FA-128
*  Bug fix
* The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)
=> Make createAccount page compliant with requirements of current dev hub prototype

src/main/resources/static/css/application.css, src/main/resources/templates/dev-hub/authentication.html, src/main/resources/templates/dev-hub/gettingStarted.html
- Fix styling issue, background appears as intended along with correct format of code.
- No GDS for this, have to use custom css for the moment.
- Fix broken link to authentication page on Getting started page.
FA-220
=> Fix styling issues with rendering example code

src/main/java/uk/gov/ch/developer/docs/controller/developer/ApplicationOverviewController.java, src/main/resources/application.properties, src/main/resources/templates/dev-hub/manageApplications.html, src/test/java/uk/gov/ch/developer/docs/controller/developer/ApplicationOverviewControllerTest.java
- Create simple html page 
- Add controller
- Add unit tests
- Modify properties file
FA-306
=> Create initial implementation of Application Overview page

src/main/resources/templates/layouts/baseLayout.html
Fixed Skip Link
No Jira ticket, piggy back off the previous FA-385
=> Fixed Skip Link

src/main/java/uk/gov/ch/developer/docs/models/nav/NavBarModelBuilder.java
Removing sonar suppression comment that was accidentally copy pasted
fa-344
=> Removed unnecessary sonar suppression.

src/main/resources/templates/dev-hub/getStarted.html
Fungai identified an old incorrect paragraph.
FA-210
=> Corrected paragraph content.

src/main/resources/templates/dev-hub/developerGuidelines.html
Fungai spotted item should be renamed
FA-210 https://companieshouse.atlassian.net/browse/FA-210 
=> Renamed content list item.

src/main/resources/templates/dev-hub/developerGuidelines.html
Apparently there were two items than needed renaming
FA-210 https://companieshouse.atlassian.net/browse/FA-210
=> Re-Renamed content list item.

pom.xml
Removed breaking lines from repository section of pom to facilitate test-analyse in concourse
=> Removed breaking lines from repository section of pom

src/main/java/uk/gov/ch/developer/docs/controller/developer/UserCallbackController.java, src/main/java/uk/gov/ch/oauth/IIdentityProvider.java, src/main/java/uk/gov/ch/oauth/IOauth.java, src/main/java/uk/gov/ch/oauth/IdentityProvider.java, src/main/java/uk/gov/ch/oauth/OAuthToken.java, src/main/java/uk/gov/ch/oauth/Oauth2.java, src/main/java/uk/gov/ch/oauth/UserProfileResponse.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/UserCallbackControllerTest.java, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- Create OAuthToken & UserProfileResponse class to map responses from api to objects
- Use access token to get user profile
- Then set user profile which is used by user bar to display details
FA-606
=> Get User Profile

src/main/java/uk/gov/ch/developer/docs/config/NavBarConfig.java, src/main/resources/application.properties, src/main/resources/templates/fragments/userBar.html
Updated user and nav bar to latest prototype version.
https://companieshouse.atlassian.net/browse/FA-417
=> feature/fa-417 Updated user and nav bar

pom.xml, src/main/java/uk/gov/ch/developer/docs/controller/developer/SignOutController.java, src/main/resources/application.properties
Add signout controller that redirects to chs /signout
FA-390
=> Implement Signout

src/main/java/uk/gov/ch/developer/docs/config/SessionStoreConfig.java, src/main/java/uk/gov/ch/developer/docs/controller/developer/SignOutController.java
Remove sign in info from session
Set signed in to be 0 - When signing out
Delete ZXS info from cache
FA-688
=> Add local implementation of /signout

src/test/java/uk/gov/ch/developer/docs/controller/developer/SignOutControllerTest.java
- Unit test for SignOutController
FA-686
=> Add unit tests for SignOutController

src/main/java/uk/gov/ch/developer/docs/controller/developer/UserCallbackController.java, src/main/java/uk/gov/ch/oauth/IOauth.java, src/main/java/uk/gov/ch/oauth/Oauth2.java
This was done to match the perl code that we are refactoring into Java
Tests for this class will be picked up in a later ticket FA-687
FA-704
*  New feature
*  The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)
=> Introduced code where nonce value is updated to an empty value

src/main/java/uk/gov/ch/developer/docs/controller/developer/SignOutController.java, src/main/java/uk/gov/ch/oauth/IOauth.java, src/main/java/uk/gov/ch/oauth/Oauth2.java, src/main/java/uk/gov/ch/oauth/session/SessionFactory.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/SignOutControllerTest.java, src/test/java/uk/gov/ch/oauth/Oauth2Test.java
Refactored Signout Controller, lifting most of the logic to Oauth2 class, and refactored unit tests accordingly. 
FA-739
=> Feature/user oauth/refactor signout controller

pom.xml, src/main/java/uk/gov/ch/oauth/Oauth2.java, src/test/java/uk/gov/ch/oauth/Oauth2Test.java
- Add method to check for invalid response from server
- Check for client or server error and respond appropriately,
- Add unit test class for Oauth2.java to check how app responds to 403 & 201 responses.
FA-706
=> Error handling for User Profile

src/main/java/uk/gov/ch/oauth/Oauth2.java, src/main/java/uk/gov/ch/oauth/tokens/OAuthToken.java, src/main/java/uk/gov/ch/oauth/tokens/SessionSignInModifier.java, src/main/java/uk/gov/ch/oauth/tokens/SignInInfoMap.java, src/main/java/uk/gov/ch/oauth/tokens/UserProfileResponse.java, src/test/java/uk/gov/ch/oauth/tokens/OAuthTokenTest.java, src/test/java/uk/gov/ch/oauth/tokens/SessionSignInModifierTest.java, src/test/java/uk/gov/ch/oauth/tokens/SignInInfoMapTest.java, src/test/java/uk/gov/ch/oauth/tokens/UserProfileResponseTest.java
Refactoring of Tokens in preparation to be moved into Oauth library
https://companieshouse.atlassian.net/browse/FA-748
=> Improved testing of token classes.

pom.xml, src/main/java/uk/gov/ch/oauth/OAuth2StateHandler.java, src/test/java/uk/gov/ch/oauth/OAuth2StateHandlerTest.java
Added tests, slight changes to the Logger logic.
https://companieshouse.atlassian.net/browse/FA-753
=> Feature/user oauth/fa 753 refactor state handler

pom.xml, src/main/java/uk/gov/ch/developer/docs/config/OauthBean.java, src/main/java/uk/gov/ch/developer/docs/controller/developer/UserCallbackController.java, src/main/java/uk/gov/ch/oauth/IOAuthCoordinator.java, src/main/java/uk/gov/ch/oauth/OAuthCoordinator.java, src/main/java/uk/gov/ch/oauth/exceptions/UnauthorisedException.java, src/main/java/uk/gov/ch/oauth/identity/IdentityProvider.java, src/main/java/uk/gov/ch/oauth/tokens/SignInInfoMap.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/UserCallbackControllerTest.java, src/test/java/uk/gov/ch/oauth/OAuthCoordinatorTest.java, src/test/java/uk/gov/ch/oauth/identity/IdentityProviderTests.java, src/test/java/uk/gov/ch/oauth/tokens/SignInInfoMapTest.java
Created coordinator class to remove objects from user implementation code
JIRA Ticket Number
https://companieshouse.atlassian.net/browse/FA-754
=> Feature/user oauth/fa 754 refactor callback

src/test/java/uk/gov/ch/oauth/OAuth2StateHandlerTest.java
Change expected exception to correct one
=> Change expected exception to ParseException 

src/main/java/uk/gov/ch/oauth/Oauth2.java, src/main/java/uk/gov/ch/oauth/session/SessionFactory.java, src/test/java/uk/gov/ch/oauth/Oauth2Test.java
- Move buildSessionCookie() into SessionFactory
- FA-752
=> Add unit tests for OAuth2 class

src/main/java/uk/gov/ch/developer/docs/config/OauthBean.java, src/main/java/uk/gov/ch/oauth/OAuthCoordinator.java, src/main/java/uk/gov/ch/oauth/Oauth2.java, src/test/java/uk/gov/ch/oauth/Oauth2Test.java
- Return empty OAuthToken object is response is not of 2xx
- Add relevant unit tests
- Return null if token is null or empty
- FA-770
=> Implement error handling for access token

src/main/resources/templates/dev-hub/getStarted.html, src/main/resources/templates/dev-hub/home.html
Corrected link addresses that were pointing to incorrect internal locations
https://companieshouse.atlassian.net/browse/FA-865
=> Corrected Link Addresses

pom.xml
Update pom.xml web-security-version to include work with new scopes and permissions
FA-526
*  New feature
*  The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)
=> Update web-security version 

pom.xml
Changed version number to match latest release https://github.com/companieshouse/oauth-signin-java-library
https://companieshouse.atlassian.net/browse/FA-1003
=> Updated version number

pom.xml
-alter parent pom to be companies-house-parent
-add spring dependency versions
https://companieshouse.atlassian.net/browse/FA-781
=> fa-781 Update pom docs.developer

README.md
- Add readme with information on how to setup the app locally
- FA-1031
=> Add readme to give further information on how to setup app locally

pom.xml
-cleaned pom
-updated parent pom to more recent version
https://companieshouse.atlassian.net/browse/FA-1010
=> fa-1010 clean pom docs.developer

src/main/resources/templates/dev-hub/home.html, src/main/resources/templates/layouts/baseLayout.html
* Removed beta banner layout fragment
* Removed paragraphs relating to beta
[BI-8724](https://companieshouse.atlassian.net/browse/BI-8724)
=> BI-8724 Remove Beta banner and paragraph reference

README.md
In order to avoid future confusions about versioning Mongo for this app. Removed the reference to Mongo that created the confusion.
https://companieshouse.atlassian.net/browse/BI-8738
=> Remove MongoDB reference from Readme

pom.xml
* Update log4j dependency to 2.16.0
* Tested locally, working
[DEBT-1443](https://companieshouse.atlassian.net/browse/DEBT-1443)
[tree.txt](https://github.com/companieshouse/docs.developer.ch.gov.uk/files/7720752/tree.txt)
=> DEBT-1443 Update log4j dependency

src/main/resources/templates/dev-hub/home.html
Updated text for the home webpage.
DSND-1912
=> Updated text for home.html

pom.xml
Add sonar maven plugin to fix test-analyse task.
=> Add sonar maven plugin

.idea/compiler.xml, .idea/encodings.xml, .idea/misc.xml, .idea/modules.xml, Tiltfile.dev, pom.xml, src/main/java/uk/gov/ch/developer/docs/controller/developer/SignInController.java, src/main/java/uk/gov/ch/developer/docs/controller/developer/SignOutController.java, src/main/java/uk/gov/ch/developer/docs/controller/developer/UserCallbackController.java, src/main/java/uk/gov/ch/developer/docs/controller/errors/DefaultErrorController.java, src/main/java/uk/gov/ch/developer/docs/interceptor/LoggingInterceptor.java, src/main/java/uk/gov/ch/developer/docs/security/WebSecurity.java, src/main/resources/application.properties, src/test/java/uk/gov/ch/developer/docs/ApplicationVariables.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/ApplicationOverviewControllerTest.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/AuthenticationControllerTest.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/CreateAccountControllerTest.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/DeveloperGuidelinesControllerTest.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/GetStartedControllerTest.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/HistoricHomeControllerTest.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/HomeControllerTest.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/OverviewControllerTest.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/SignInControllerTest.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/SignOutControllerTest.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/UserCallbackControllerTest.java, src/test/java/uk/gov/ch/developer/docs/controller/errors/DefaultErrorControllerTest.java, src/test/java/uk/gov/ch/developer/docs/interceptor/LoggingInterceptorTest.java, src/test/java/uk/gov/ch/developer/docs/models/nav/NavBarItemTest.java
* Migrated this application from Java 8 to Java 21, and from Spring Boot 2.2.0.RELEASE to Spring Boot 3.3.3.
* Tested successfully in Tilt.
* No attempt has been made to tackle security vulnerabilities as yet. Such changes will be dealt with in (a) separate PR(s).
[JU-548](https://companieshouse.atlassian.net/browse/JU-548)
[JU-548]: https://companieshouse.atlassian.net/browse/JU-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JU-548: Migrate to Java 21 and Spring Boot 3.3.3

src/main/java/uk/gov/ch/developer/docs/config/NavBarConfig.java, src/main/java/uk/gov/ch/developer/docs/controller/AbstractPageController.java, src/main/java/uk/gov/ch/developer/docs/controller/developer/SignOutController.java, src/main/java/uk/gov/ch/developer/docs/controller/errors/DefaultErrorController.java, src/main/java/uk/gov/ch/developer/docs/interceptor/LoggingInterceptor.java, src/main/java/uk/gov/ch/developer/docs/models/nav/NavItemList.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/CreateAccountControllerTest.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/DeveloperGuidelinesControllerTest.java, src/test/java/uk/gov/ch/developer/docs/models/nav/NavBarItemTest.java
* A number of tweaks that are appropriate given we are now using Java 21 for this app.
[JU-548](https://companieshouse.atlassian.net/browse/JU-548)
[JU-548]: https://companieshouse.atlassian.net/browse/JU-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JU-548: Make the tweaks suggested by Sonar

terraform/groups/ecs-service/main.tf
=> JU-548 Update terraform modules to latest

Makefile
=> JU-548 Update Makefile for dependency check

ecs-image-build/Dockerfile
=> JU-548 Update Dockerfile

pom.xml, src/main/resources/application.properties, terraform/groups/ecs-service/locals.tf
=> JU-548 Add healthcheck and update pom

src/main/resources/templates/layouts/baseLayout.html
=> JU-548 Update template syntax

README.md, terraform/groups/ecs-service/locals.tf
=> Poke pipeline

terraform/groups/ecs-service/main.tf
This reverts commit c056e874f705516ee4cb80922a8adc2832d94c8a.
=> Revert "DVOP-3031 Bumping the module version"

README.md, terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/variables.tf
=> Clean start

pom.xml, src/main/java/uk/gov/ch/developer/docs/controller/developer/SignOutController.java, src/main/resources/application.properties, src/test/java/uk/gov/ch/developer/docs/controller/developer/SignOutControllerTest.java
* Bumped the version of the java session handler
* Removed the old signout method that no longer exists in the Java session handler
* Added a new signout redirect URL to the SignOutController
[CC-2119](https://companieshouse.atlassian.net/browse/CC-2119)
[CC-2119]: https://companieshouse.atlassian.net/browse/CC-2119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CC-2119: Updated the Java session handler version

pom.xml
* Bumped the versions of Spring and log4J
[CC-2119](https://companieshouse.atlassian.net/browse/CC-2119)
[CC-2119]: https://companieshouse.atlassian.net/browse/CC-2119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CC-2119: Updated dependency versions

pom.xml, src/main/java/uk/gov/ch/developer/docs/DocsWebApplication.java, src/main/java/uk/gov/ch/developer/docs/config/InterceptorConfig.java, src/main/java/uk/gov/ch/developer/docs/controller/developer/SignInController.java, src/main/java/uk/gov/ch/developer/docs/controller/developer/SignOutController.java, src/main/java/uk/gov/ch/developer/docs/controller/developer/UserCallbackController.java, src/test/java/uk/gov/ch/developer/docs/controller/developer/SignOutControllerTest.java
=> FCS-41 Improve logging

terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf
=> FCS-41 align terraform with oauth-web

terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf
Reverts companieshouse/docs.developer.ch.gov.uk#163
=> Revert "FCS-41 align terraform with oauth-web"

pom.xml
Add sonar properties to pom
[FCS-47](https://companieshouse.atlassian.net/browse/FCS-47)
[FCS-47]: https://companieshouse.atlassian.net/browse/FCS-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FCS-47 Update sonarqube
